version: '3'
services:
  book-service:
    image: jairum/api-books:1.0
    deploy:
      replicas: 1
    ports:
      - "8081:8081"
  author-service:
    image: jairum/api-autores:1.0
    deploy:
      replicas: 1
    environment:
      datasource.db-kind: postgresql
      datasource.username: ubuntu
      datasource.password: 12345678
      datasource.jdbc.url: jdbc:postgresql://181.215.242.75:10007/distribuida
    ports:
      - "8082:8082"
  front-service:
    image: jairum/app-libreria:1.0
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    depends_on:
      - book-service
      - author-service

